# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/simon/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /home/simon/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/simon/CLionProjects/TextGenerator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/simon/CLionProjects/TextGenerator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/simon/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/CLionProjects/TextGenerator/CMakeFiles /home/simon/CLionProjects/TextGenerator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/CLionProjects/TextGenerator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TextGenerator

# Build rule for target.
TextGenerator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TextGenerator
.PHONY : TextGenerator

# fast build rule for target.
TextGenerator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/build
.PHONY : TextGenerator/fast

src/frequency_table.o: src/frequency_table.c.o
.PHONY : src/frequency_table.o

# target to build an object file
src/frequency_table.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/frequency_table.c.o
.PHONY : src/frequency_table.c.o

src/frequency_table.i: src/frequency_table.c.i
.PHONY : src/frequency_table.i

# target to preprocess a source file
src/frequency_table.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/frequency_table.c.i
.PHONY : src/frequency_table.c.i

src/frequency_table.s: src/frequency_table.c.s
.PHONY : src/frequency_table.s

# target to generate assembly for a file
src/frequency_table.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/frequency_table.c.s
.PHONY : src/frequency_table.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/main.c.s
.PHONY : src/main.c.s

src/multi_process.o: src/multi_process.c.o
.PHONY : src/multi_process.o

# target to build an object file
src/multi_process.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/multi_process.c.o
.PHONY : src/multi_process.c.o

src/multi_process.i: src/multi_process.c.i
.PHONY : src/multi_process.i

# target to preprocess a source file
src/multi_process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/multi_process.c.i
.PHONY : src/multi_process.c.i

src/multi_process.s: src/multi_process.c.s
.PHONY : src/multi_process.s

# target to generate assembly for a file
src/multi_process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/multi_process.c.s
.PHONY : src/multi_process.c.s

src/single_threaded.o: src/single_threaded.c.o
.PHONY : src/single_threaded.o

# target to build an object file
src/single_threaded.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/single_threaded.c.o
.PHONY : src/single_threaded.c.o

src/single_threaded.i: src/single_threaded.c.i
.PHONY : src/single_threaded.i

# target to preprocess a source file
src/single_threaded.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/single_threaded.c.i
.PHONY : src/single_threaded.c.i

src/single_threaded.s: src/single_threaded.c.s
.PHONY : src/single_threaded.s

# target to generate assembly for a file
src/single_threaded.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/single_threaded.c.s
.PHONY : src/single_threaded.c.s

src/text_generator.o: src/text_generator.c.o
.PHONY : src/text_generator.o

# target to build an object file
src/text_generator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/text_generator.c.o
.PHONY : src/text_generator.c.o

src/text_generator.i: src/text_generator.c.i
.PHONY : src/text_generator.i

# target to preprocess a source file
src/text_generator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/text_generator.c.i
.PHONY : src/text_generator.c.i

src/text_generator.s: src/text_generator.c.s
.PHONY : src/text_generator.s

# target to generate assembly for a file
src/text_generator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextGenerator.dir/build.make CMakeFiles/TextGenerator.dir/src/text_generator.c.s
.PHONY : src/text_generator.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TextGenerator"
	@echo "... src/frequency_table.o"
	@echo "... src/frequency_table.i"
	@echo "... src/frequency_table.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/multi_process.o"
	@echo "... src/multi_process.i"
	@echo "... src/multi_process.s"
	@echo "... src/single_threaded.o"
	@echo "... src/single_threaded.i"
	@echo "... src/single_threaded.s"
	@echo "... src/text_generator.o"
	@echo "... src/text_generator.i"
	@echo "... src/text_generator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

